### ISSUE TITLE
OpenBSD oddities

### ISSUE THREAD

**Issue by Lewiscowles1986** [fcambus/logswan#17]
Hello 👋 

Awesome tool

Using the OpenBSD `pkg_add logswan` I encountered this program unable to parse https access.log

```
Processed 25 lines in 0.035031 seconds
{
   "date": "2019-02-10 14:14:07",
   "generator": "Logswan 2.0.2",
   "file_name": "-",
   "file_size": 0,
   "processed_lines": 25,
   "invalid_lines": 25,
   "bandwidth": 0,
...
```

* First thoughts were, how to change log format to be compatible. By default it looks like OpenBSD is incompatible.
* So I changed to `log style common`, which should work. It didn't
* So I changed to `log style combined`, still didn't work

I glanced at differences between the provided examples and my own logs and could find few differences. At this point I kinda gave up.

Then I found the following from the person that suggested logswan as an alternative to google analytics

https://github.com/romanzolotarev/romanzolotarev.com/blob/master/bin/log#L10

It seems in-order to analyse logs, I need to pass through `cut` utility.

`sudo cat /var/www/logs/access.log | cut -d" " -f2- | logswan -`

I'm unsure if this should be added to troubleshooting, but it fixed `log style combined` and `log style common` httpd on OpenBSD 6.4

**Comment by fcambus** [comment]
That's because OpenBSD's httpd does not strictly respect the [common](https://httpd.apache.org/docs/1.3/logs.html#common) or [combined](https://httpd.apache.org/docs/1.3/logs.html#combined) log formats, it always prepends virtualhosts.

I'm not sure why it is this way, but it's probably too late to change this in httpd now, so you will have to filter the logs before feeding them to logswan.
